apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
  - image: bitnami/redis
    imagePullPolicy: IfNotPresent
    name: redis
    securityContext:
      runAsNonRoot: true
      readOnlyRootFilesystem: true
  restartPolicy: Always
