apiVersion: v1
kind: Pod
metadata:
  name: data
spec:
  containers:
  - image: mysql:5.5
    name: db
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: foobar
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: root
  volumes:
  - name: foobar
    persistentVolumeClaim:
      claimName: myclaim
